### ISSUE TITLE
Mgmt0 interface not created for APIC devices

### ISSUE THREAD

**Issue by jasonjuenger** [nautobot/nautobot-plugin-ssot#185]
### Environment
* Python version:  3.7.15
* Nautobot version:  1.5.4
* nautobot-ssot-aci version:  1.0.0

### Expected Behavior
Plugin should create mgmt0 interface object for Cisco ACI APIC devices so an IP Address object can be correctly created and assigned to the interface.

### Observed Behavior
Create() method in NautobotIPAddress class queries for the interface(s) belonging to an APIC device in order to create an IP Address object and associate it with the relevant APIC interface. The plugin does not currently create Interface objects for APICs, specifically mgmt0, so the query for the device interfaces fails resulting in the following error.

```Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/usr/local/lib/python3.7/site-packages/nautobot_ssot/jobs/base.py", line 167, in sync_data
    self.execute_sync()
  File "/usr/local/lib/python3.7/site-packages/nautobot_ssot/jobs/base.py", line 95, in execute_sync
    self.source_adapter.sync_to(self.target_adapter, flags=self.diffsync_flags)
  File "/usr/local/lib/python3.7/site-packages/diffsync/__init__.py", line 579, in sync_to
    target.sync_from(self, diff_class=diff_class, flags=flags, callback=callback, diff=diff)
  File "/usr/local/lib/python3.7/site-packages/diffsync/__init__.py", line 557, in sync_from
    result = syncer.perform_sync()
  File "/usr/local/lib/python3.7/site-packages/diffsync/helpers.py", line 327, in perform_sync
    changed |= self.sync_diff_element(element)
  File "/usr/local/lib/python3.7/site-packages/diffsync/helpers.py", line 367, in sync_diff_element
    changed, modified_model = self.sync_model(src_model=src_model, dst_model=dst_model, ids=ids, attrs=attrs)
  File "/usr/local/lib/python3.7/site-packages/diffsync/helpers.py", line 416, in sync_model
    dst_model = self.model_class.create(diffsync=self.dst_diffsync, ids=ids, attrs=attrs)
  File "/usr/local/lib/python3.7/site-packages/nautobot_ssot_aci/diffsync/models/nautobot.py", line 347, in create
    .interfaces.get(name=attrs["interface"])
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/cacheops/query.py", line 351, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
nautobot.dcim.models.device_components.Interface.DoesNotExist: Interface matching query does not exist.
```

### Steps to Reproduce
1. Discover an ACI fabric with dry-run disabled and at least 1 physical APIC (not tested against ACI Simulator)

**Comment by jtdub** [comment]
## Current Status (codebase review, February 2026)

This issue was filed against the standalone `nautobot-ssot-aci` plugin. That plugin has since been merged into the `nautobot-ssot` monorepo. A review of the current code shows this is **mostly resolved**, with one remaining gap.

### What has been fixed

**1. The crash is gone.**

`NautobotIPAddress.create()` in `nautobot_ssot/integrations/aci/diffsync/models/nautobot.py` now wraps the interface lookup in a `try/except OrmInterface.DoesNotExist` block. If the `mgmt0` interface isn't found, a warning is logged and the IP address is still created — the sync job no longer fails.

**2. `mgmt0` interface creation was added for most APIC models.**

`AciAdapter.load_interfaces()` now includes a loop over each device type's YAML file that creates interface objects for any interface matching `^Eth[0-9]|^mgmt[0-9]`. Since APIC controllers don't expose physical interfaces via the ACI `l1PhysIf` API class, their interfaces must come from these YAML definitions.

The following APIC device-type YAML files all define `mgmt0` and are handled correctly:
- `APIC-SERVER-L3.yaml` ✅
- `APIC-SERVER-M1.yaml` ✅
- `APIC-SERVER-M3.yaml` ✅
- `APIC-SIM.yaml` ✅

### Remaining gap

`APIC-SERVER-L2.yaml` does **not** define a `mgmt0` interface. For environments running APIC-L2 hardware, the `mgmt0` interface still won't be created in Nautobot, and the OOB management IP will be created without being assigned to an interface. This results in a warning log entry rather than a crash, but the interface association is still missing.

### Suggested fix

Add `mgmt0` to the interfaces list in `APIC-SERVER-L2.yaml`, consistent with the other APIC model YAML files:

```yaml
  - name: mgmt0
    type: 10gbase-t
    mgmt_only: true
```
