### ISSUE TITLE
Error on Delete Orphaned Data Compliance Data from metrics

### ISSUE THREAD

**Issue by etiennelatulippe** [nautobot/nautobot-plugin-ssot#248]
### Environment
* Python version:  3.11.6
* Nautobot version:  2.0.1
* nautobot-ssot version:  2.0.0

### Expected Behavior
Being able to migrate from nautobot v1.62 

### Observed Behavior

```
19:27:07.153 DEBUG   nautobot.core.celery: Importing system Jobs
19:27:07.157 WARNING nautobot.extras.utils: Job class "CloudVisionDataSource" name "CloudVision ⟹ Nautobot" is not unique, changing to "CloudVision ⟹ Nautobot (2)".
19:27:07.162 INFO    nautobot.extras.utils: Refreshed Job "SSoT - Arista CloudVision: CloudVision ⟹ Nautobot (2)" from <CloudVisionDataSource>
19:27:07.163 WARNING nautobot.extras.utils: Job class "CloudVisionDataTarget" name "Nautobot ⟹ CloudVision" is not unique, changing to "Nautobot ⟹ CloudVision (2)".
19:27:07.166 INFO    nautobot.extras.utils: Refreshed Job "SSoT - Arista CloudVision: Nautobot ⟹ CloudVision (2)" from <CloudVisionDataTarget>
19:27:07.169 INFO    nautobot.extras.utils: Refreshed Job "System Jobs: Git Repository: Sync" from <GitRepositorySync>
19:27:07.175 INFO    nautobot.extras.utils: Refreshed Job "System Jobs: Git Repository: Dry-Run" from <GitRepositoryDryRun>
19:27:07.179 INFO    nautobot.extras.utils: Refreshed Job "nautobot_data_validation_engine.jobs: Run Registered Data Compliance Rules" from <RunRegisteredDataComplianceRules>
19:27:07.183 INFO    nautobot.extras.utils: Refreshed Job "nautobot_data_validation_engine.jobs: Delete Orphaned Data Compliance Data" from <DeleteOrphanedDataComplianceData>
Traceback (most recent call last):
  File "/usr/local/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/cli/__init__.py", line 54, in main
    run_app(
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/runner/runner.py", line 297, in run_app
    management.execute_from_command_line([runner_name, command] + command_args)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 268, in handle
    emit_post_migrate_signal(
  File "/usr/local/lib/python3.11/site-packages/django/core/management/sql.py", line 42, in emit_post_migrate_signal
    models.signals.post_migrate.send(
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/core/apps/__init__.py", line 798, in post_migrate_send_nautobot_database_ready
    nautobot_database_ready.send(sender=app_conf, app_config=app_conf, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
           ^
  File "/usr/local/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nautobot/extras/plugins/__init__.py", line 628, in discover_metrics
    for metric_instance in metric():
  File "/usr/local/lib/python3.11/site-packages/nautobot_ssot/metrics.py", line 27, in metric_ssot_jobs
    if issubclass(job.job_class, (DataSource, DataTarget)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class`
```

### Steps to Reproduce
1. Having a nautobot 1.6.2 with a dataset and that is using nautobot_ssot
2.  $nautobot-server migrate

**Comment by Kircheneer** [comment]
This has me possibly wanting to wrap the metrics in a try except, second time I have seen an error like this with the metrics extensibility causing crashes.

**Comment by Kircheneer** [comment]
Could be something to do in core Nautobot as well.

**Comment by Kircheneer** [comment]
Do you have any custom SSoT jobs or just the ones that come with this plugin?

**Comment by etiennelatulippe** [comment]
Hi Kircheneer, yes I have custom SSoT Jobs. Thanks
