### ISSUE TITLE
NautobotModel many-to-one relationships don't always look at all __ fields

### ISSUE THREAD

**Issue by gioccher** [nautobot/nautobot-plugin-ssot#294]
### Environment
* Python version:  3.9.18
* Nautobot version:  1.6.6
* nautobot-ssot version:  1.6.0

### Expected Behavior
both the `lag__name` and `lag__device__name` fields are always used to determine the target.
The LAG gets updated

### Observed Behavior
```
An exception occurred: ValueError: Found multiple instances for lag wit: {'name': 'Port-Channel9'}

Traceback (most recent call last):
  File "/opt/nautobot/.local/lib/python3.9/site-packages/nautobot_ssot/contrib.py", line 409, in _lookup_and_set_foreign_keys
    related_object = related_model.objects.get(**related_model_dict)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cacheops/query.py", line 353, in get
    return qs._no_monkey.get(qs, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
nautobot.dcim.models.device_components.Interface.MultipleObjectsReturned: get() returned more than one Interface -- it returned 2!
```

### Steps to Reproduce
1. create a device "device1" with an interface "Ethernet1" of type "Other", and interfaces "Port-Channel1" and "Port-Channel9" of type LAG
2. run the job below: it will work fine
3. modify the job replacing the line `loaded_interface.lag__name = "Port-Channel1"` with `loaded_interface.lag__name = "Port-Channel9"`
4. run the job again: you'll receive the error

I think this happens because Diffsync will remember that lag__name has changed, but won't track lag__device__name because that has not changed and during the actual run it will search for interfaces only using lag__name. It works fine if the interface doesn't have a LAG set (diffsync will track changes to both lag__name and lag__device__name )

```
from typing import Annotated, List, Optional, TypedDict  # noqa: UP035

from diffsync import DiffSync
from diffsync.enum import DiffSyncFlags, DiffSyncModelFlags
from nautobot.dcim.models import Interface
from nautobot.extras.datasources import ensure_git_repository
from nautobot.extras.jobs import Job
from nautobot_ssot.contrib import CustomFieldAnnotation, NautobotAdapter, NautobotModel
from nautobot_ssot.jobs import DataSource


class InterfaceModel(NautobotModel):
    """DiffSync model for Interfaces"""
    _model = Interface
    _modelname = "interface"
    _identifiers = ("name", "device__name")
    _attributes = (
        "description",
        "enabled",
        "mode",
        "status__slug",
        "lag__name",
        "lag__device__name",
    )

    name: str
    device__name: str
    description: Optional[str]
    enabled: bool
    mode: Optional[str]
    status__slug: str
    lag__name: Optional[str]
    lag__device__name: Optional[str]
    

class TargetNautobotAdapter(NautobotAdapter):
    interface = InterfaceModel
    top_level = ("interface", )
    
    def __init__(self, *args, job: Job, **kwargs):
        super().__init__(*args, **kwargs)
        self.job = job

class SourceGitAdapter(DiffSync):
    interface = InterfaceModel
    top_level = ("interface", )

    def __init__(self, *args, job: Job, **kwargs):
        super().__init__(*args, **kwargs)
        self.job = job

    def load(self):
        loaded_interface = self.interface(
            name="Ethernet1",
            device__name="device1",
            description="whatever1",
            enabled=True,
            mode="access",
            status__slug="active",
        )
        loaded_interface.lag__device__name = loaded_interface.device__name
        loaded_interface.lag__name = "Port-Channel1"
        self.add(loaded_interface)



class GitDataSource(DataSource, Job):
    """SSoT Job class."""
    class Meta:
        name = "Git Data Source"
        
    def __init__(self):
        super().__init__()
        self.diffsync_flags = (self.diffsync_flags | DiffSyncFlags.SKIP_UNMATCHED_DST)
        self.debug = True

    def load_source_adapter(self):
        self.source_adapter = SourceGitAdapter(job=self)
        self.source_adapter.load()

    def load_target_adapter(self):
        self.target_adapter = TargetNautobotAdapter(job=self)
        self.target_adapter.load()

jobs = [GitDataSource]
```

**Comment by gioccher** [comment]
@Kircheneer any chance for this to be triaged? Hate to be the guy that pings the devs directly but this issue feels like it fell through the cracks. Thanks!

**Comment by gioccher** [comment]
for anyone affected by this (which is more common in NB 2.x thanks to the removal of slugs), you can override update as a workaround in the `XXXModel(NautobotModel)` classes that need it
```
def update(self, attrs: dict):
    if "vrf__namespace__name" in attrs and "vrf__name" not in attrs:
        attrs["vrf__name"] = self.vrf__name
    if "vrf__name" in attrs and "vrf__namespace__name" not in attrs:
        attrs["vrf__namespace__name"] = self.vrf__namespace__name
    return super().update(attrs)
```

**Comment by gioccher** [comment]
Hi, I just tried SSOT 2.5.0 on NB 2.1.8 after removing my update() workaround and it doesn't crash anymore but it also does not perform the requested update.
Running the sync job multiple times (without dry-run) it keeps finding the same changes and not acting on them
