### ISSUE TITLE
diff database representation is too big for jsonb field when syncing a lot of objects.

### ISSUE THREAD

**Issue by Kircheneer** [nautobot/nautobot-plugin-ssot#67]
### Environment
* Python version:  3.9
* Nautobot version:  1.4.7
* nautobot-ssot version: 1.1.0

### Expected Behavior

My SSoT job with a diffsync JSON diff representation of >268435455 bytes rusn through without an error.

This is 36126 sites with a good couple of fields and custom fields.

### Observed Behavior

```
An exception occurred: OperationalError: total size of jsonb object elements exceeds the maximum of 268435455 bytes LINE 1: ...c_memory_peak" = NULL, "dry_run" = true, "diff" = '{"site": ... ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
psycopg2.errors.ProgramLimitExceeded: total size of jsonb object elements exceeds the maximum of 268435455 bytes
LINE 1: ...c_memory_peak" = NULL, "dry_run" = true, "diff" = '{"site": ...
                                                             ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/nautobot_ssot/jobs/base.py", line 332, in run
    self.sync_data()
  File "/usr/local/lib/python3.7/site-packages/nautobot_ssot/jobs/base.py", line 155, in sync_data
    self.calculate_diff()
  File "/usr/local/lib/python3.7/site-packages/nautobot_ssot/jobs/base.py", line 84, in calculate_diff
    self.sync.save()
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 740, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 778, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 859, in _save_table
    forced_update)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 912, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 802, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1559, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1175, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/cacheops/transaction.py", line 97, in execute
    result = self._no_monkey.execute(self, sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/site-packages/django_prometheus/db/common.py", line 71, in execute
    return super().execute(*args, **kwargs)
django.db.utils.OperationalError: total size of jsonb object elements exceeds the maximum of 268435455 bytes
LINE 1: ...c_memory_peak" = NULL, "dry_run" = true, "diff" = '{"site": ...
                                                             ^
```

### Steps to Reproduce
1. Have a lot of objects to sync such that the diff of the SSoT job becomes bigger than 268435455 bytes
2. Execute the SSoT job

**Comment by chadell** [comment]
thanks @Kircheneer . This is an interesting issue to address.

**Comment by chadell** [comment]
@Kircheneer a quick workaround, until we find a better solution,  would be to truncate the size of the log to some limit to avoid hitting the OperationalError? Maybe adding a final message to explain that some log was truncated?

**Comment by Kircheneer** [comment]
Yes, that sounds like a good plan.

**Comment by Kircheneer** [comment]
Implementation plan:

- Enforce a limit check of the size, raising a warning when it was not possible to persist it.
- Offer a user option to choose if the diff has to be persisted or not.

**Comment by Kircheneer** [comment]
Quick note on the topic of compressed fields: https://gist.github.com/tomfa/665f8a655a9218e0b4e9bd394d459934

**Comment by jmcgill298** [comment]
Should we try to use this instead of chopping off after ~1GB?

**Comment by chadell** [comment]
I think that compressing is a good workaround to include larger outputs, but even compressing, we have the risk to break it. So I think it's interesting to add a safeguard with a limit (either for compressed or uncompressed data)

**Comment by jmcgill298** [comment]
well, we couldn't set a limit on a compressed object, because uncompressing it would leave invalid JSON

**Comment by jmcgill298** [comment]
#145
